os:
  - linux
#  - windows
language: node_js
node_js:
  - 10
  - 12
  - node
cache: false


stages:
  - name: test
  - name: deploy
    if: (NOT type IN (pull_request)) AND ( branch = master OR tag =~ ^v[0-9] )

jobs:
  include:
    - stage: deploy
      name: deploy
      script: .travis/deploy_npm
  
